import { useState, useEffect, useRef, useCallback } from "react";
import {
  loadGisScript, initSemesterTokenClient, ROOT_SURVEYS_FOLDER_ID,
  SEMESTER_TOKEN_KEY, saveStoredToken, getStoredToken,
  listSubfolders, listFormsInFolder, getForm, listAllResponses,
  responsesToRows, departmentFromSurveyName,
} from "./engine/semesterSurveyModel.js";
import { GoogleDriveIcon, InlineNotice } from "./UiElements.jsx";

// Lets the main upload wizard's Drive tab pick a survey generated by the Semester
// Survey Generator (browsing {root}/{year}/{semester}/{type}) instead of only listing
// flat spreadsheet files. Needs its own OAuth token because Forms responses use
// the Forms API in addition to Drive; the token also allows saving generated
// reports beside the original form inside its survey-type folder.
//
// Shares its persisted token (SEMESTER_TOKEN_KEY, same scope/client as
// SemesterSurveys.jsx) so connecting once there — or here — covers both; and once that
// token expires, a silent requestAccessToken({prompt:""}) is tried before ever falling
// back to the visible connect button (see semesterSurveyModel.js for why).
function useSemesterAuth(enabled = true) {
  const [token, setToken] = useState(() => getStoredToken(SEMESTER_TOKEN_KEY));
  const [connecting, setConnecting] = useState(false);
  const [authError, setAuthError] = useState("");
  const clientRef = useRef(null);
  const explicitRef = useRef(false);
  const triedSilent = useRef(false);

  const ensureClient = useCallback(async () => {
    await loadGisScript();
    if (!clientRef.current) {
      clientRef.current = initSemesterTokenClient({
        onToken: (t, expiresIn) => {
          setToken(t);
          saveStoredToken(SEMESTER_TOKEN_KEY, t, expiresIn);
          setConnecting(false);
        },
        onError: e => {
          setConnecting(false);
          if (explicitRef.current) setAuthError("فشل الاتصال بـ Google: " + e);
        },
      });
    }
    return clientRef.current;
  }, []);

  useEffect(() => {
    if (!enabled || token || triedSilent.current) return;
    triedSilent.current = true;
    (async () => {
      try {
        const client = await ensureClient();
        explicitRef.current = false;
        client.requestAccessToken({ prompt: "" });
      } catch { /* ignore — falls through to the manual connect button */ }
    })();
  }, [enabled, token, ensureClient]);

  const connect = useCallback(async () => {
    setAuthError(""); setConnecting(true);
    try {
      const client = await ensureClient();
      explicitRef.current = true;
      client.requestAccessToken({ prompt: "select_account" });
    } catch (e) {
      setAuthError(e.message); setConnecting(false);
    }
  }, [ensureClient]);

  return { token, connecting, authError, connect };
}

function PickerLoader({ label = "جاري تجهيز الاستبيانات" }) {
  return (
    <div style={{ textAlign: "center", color: "rgba(255,255,255,.48)", fontSize: 13, padding: "26px 0" }}>
      <div className="loader-visual" style={{ width: 58, height: 58 }}>
        <span className="loader-ring"/><span className="loader-ring inner"/>
        <svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="#d8fff7" strokeWidth="1.8" strokeLinecap="round"><path d="M4 19V9m6 10V5m6 14v-7m6 7V3"/></svg>
      </div>
      {label}<span className="loader-dots"><i/><i/><i/></span>
    </div>
  );
}

export default function SemesterFormPicker({ onFormSelected, onAnalyzeForms, onPrepareForms, googleAuth }) {
  const localAuth = useSemesterAuth(!googleAuth);
  const auth = googleAuth ?? localAuth;
  const [years, setYears] = useState(null);
  const [year, setYear] = useState("");
  const [semesters, setSemesters] = useState(null);
  const [semester, setSemester] = useState("");
  const [forms, setForms] = useState(null);
  const [loadError, setLoadError] = useState("");
  const [loadingFormId, setLoadingFormId] = useState(null);
  const [selectedIds, setSelectedIds] = useState(() => new Set());
  const [analyzing, setAnalyzing] = useState(false);
  const [reportAuthors, setReportAuthors] = useState({ preparedBy: "", reviewer: "" });

  useEffect(() => {
    if (!auth.token) return;
    let cancelled = false;
    setYears(null); setLoadError("");
    listSubfolders(auth.token, ROOT_SURVEYS_FOLDER_ID)
      .then(fs => { if (cancelled) return; setYears(fs); setYear(y => y || fs[0]?.name || ""); })
      .catch(e => { if (!cancelled) setLoadError("فشل تحميل السنوات الدراسية: " + e.message); });
    return () => { cancelled = true; };
  }, [auth.token]);

  const yearFolder = years?.find(f => f.name === year) ?? null;

  useEffect(() => {
    if (!yearFolder) { setSemesters(null); return; }
    let cancelled = false;
    setSemesters(null);
    listSubfolders(auth.token, yearFolder.id)
      .then(fs => { if (cancelled) return; setSemesters(fs); setSemester(s => (fs.some(f => f.name === s) ? s : (fs[0]?.name || ""))); })
      .catch(e => { if (!cancelled) setLoadError("فشل تحميل الفصول الدراسية: " + e.message); });
    return () => { cancelled = true; };
  }, [auth.token, yearFolder?.id]);

  const semFolder = semesters?.find(f => f.name === semester) ?? null;

  useEffect(() => {
    if (!semFolder) { setForms(null); return; }
    let cancelled = false;
    setForms(null); setLoadError("");
    listSubfolders(auth.token, semFolder.id)
      .then(async typeFolders => {
        const perType = await Promise.all(typeFolders.map(async tf => {
          const files = await listFormsInFolder(auth.token, tf.id);
          return files.map(f => ({ ...f, surveyType: tf.name, parentId: tf.id }));
        }));
        if (!cancelled) setForms(perType.flat());
      })
      .catch(e => { if (!cancelled) setLoadError("فشل تحميل الاستبيانات: " + e.message); });
    return () => { cancelled = true; };
  }, [auth.token, semFolder?.id]);

  async function selectForm(f) {
    setLoadingFormId(f.id); setLoadError("");
    try {
      const [form, responses] = await Promise.all([getForm(auth.token, f.id), listAllResponses(auth.token, f.id)]);
      const rows = responsesToRows(form, responses);
      onFormSelected(rows, f.name, departmentFromSurveyName(f.name));
    } catch (e) {
      setLoadError("تعذّر تحميل الاستبيان: " + e.message);
    } finally {
      setLoadingFormId(null);
    }
  }

  async function analyzeForms(items, delivery = "upload") {
    if (!items.length || analyzing) return;
    if (onPrepareForms) {
      onPrepareForms(items, auth.token, { year, semester });
      return;
    }
    if (!onAnalyzeForms) return;
    const preparedBy = reportAuthors.preparedBy.trim();
    const reviewer = reportAuthors.reviewer.trim();
    if (!preparedBy || !reviewer) {
      setLoadError("يجب إدخال اسم مُعدّ التحليل واسم مراجع التحليل قبل إنشاء أي تقرير.");
      return;
    }
    setAnalyzing(true); setLoadError("");
    try { await onAnalyzeForms(items, auth.token, { delivery, reportMeta: { year, preparedBy, reviewer } }); }
    catch (e) { setLoadError("تعذّر تحليل الاستبيانات: " + e.message); }
    finally { setAnalyzing(false); }
  }

  if (!auth.token) {
    return (
      <div style={{ textAlign: "center", padding: "28px 0" }}>
        {auth.connecting ? (
          <div className="loader-visual" style={{ width: 64, height: 64 }}>
            <span className="loader-ring"/><span className="loader-ring inner"/>
            <svg width="23" height="23" viewBox="0 0 24 24" fill="none" stroke="#d8fff7" strokeWidth="1.8" strokeLinecap="round"><path d="M7 11h10M7 15h7"/><rect x="3" y="5" width="18" height="16" rx="3"/><path d="M8 3v4m8-4v4"/></svg>
          </div>
        ) : (
          <div style={{ width: 62, height: 62, display: "grid", placeItems: "center", margin: "0 auto 14px", borderRadius: 18, background: "rgba(255,255,255,.07)", border: "1px solid rgba(255,255,255,.1)" }}>
            <GoogleDriveIcon size={34} />
          </div>
        )}
        <div style={{ color: "rgba(255,255,255,.5)", fontSize: 13, marginBottom: 18 }}>
          تصفح الاستبيانات التي أنشأها "استبيانات الفصل الدراسي" حسب السنة والفصل
        </div>
        <button className="btn btn-primary btn-sm" disabled={auth.connecting} onClick={auth.connect}>
          {auth.connecting ? <>جاري الاتصال<span className="loader-dots"><i/><i/><i/></span></> : "الاتصال بـ Google"}
        </button>
        <InlineNotice text={auth.authError} style={{ marginTop: 10 }} />
      </div>
    );
  }

  return (
    <div>
      <div style={{ display: "flex", gap: 12, flexWrap: "wrap", marginBottom: 16 }}>
        <div style={{ flex: "1 1 160px" }}>
          <div style={{ color: "rgba(255,255,255,.5)", fontSize: 11, marginBottom: 5 }}>السنة الدراسية</div>
          <select value={year} onChange={e => setYear(e.target.value)}
            style={{ width: "100%", padding: "8px 12px", borderRadius: 8, border: "1px solid rgba(255,255,255,.18)", background: "rgba(255,255,255,.06)", color: "#fff", fontFamily: "'Cairo',sans-serif", fontSize: 13 }}>
            {(years ?? []).map(f => <option key={f.id} value={f.name} style={{ color: "#000" }}>{f.name}</option>)}
          </select>
        </div>
        <div style={{ flex: "1 1 160px" }}>
          <div style={{ color: "rgba(255,255,255,.5)", fontSize: 11, marginBottom: 5 }}>الفصل الدراسي</div>
          <select value={semester} onChange={e => setSemester(e.target.value)}
            style={{ width: "100%", padding: "8px 12px", borderRadius: 8, border: "1px solid rgba(255,255,255,.18)", background: "rgba(255,255,255,.06)", color: "#fff", fontFamily: "'Cairo',sans-serif", fontSize: 13 }}>
            {(semesters ?? []).map(f => <option key={f.id} value={f.name} style={{ color: "#000" }}>{f.name}</option>)}
          </select>
        </div>
        {!onPrepareForms && <div style={{ flex: "1 1 180px" }}>
          <div style={{ color: "rgba(255,255,255,.5)", fontSize: 11, marginBottom: 5 }}>مُعدّ التحليل *</div>
          <input value={reportAuthors.preparedBy} required placeholder="الاسم الكامل" onChange={e => setReportAuthors(a => ({ ...a, preparedBy: e.target.value }))}
            style={{ width: "100%", padding: "8px 12px", borderRadius: 8, border: "1px solid rgba(255,255,255,.18)", background: "rgba(255,255,255,.06)", color: "#fff", fontFamily: "'Cairo',sans-serif", fontSize: 13 }} />
        </div>}
        {!onPrepareForms && <div style={{ flex: "1 1 180px" }}>
          <div style={{ color: "rgba(255,255,255,.5)", fontSize: 11, marginBottom: 5 }}>مراجع التحليل *</div>
          <input value={reportAuthors.reviewer} required placeholder="الاسم الكامل" onChange={e => setReportAuthors(a => ({ ...a, reviewer: e.target.value }))}
            style={{ width: "100%", padding: "8px 12px", borderRadius: 8, border: "1px solid rgba(255,255,255,.18)", background: "rgba(255,255,255,.06)", color: "#fff", fontFamily: "'Cairo',sans-serif", fontSize: 13 }} />
        </div>}
      </div>

      <InlineNotice text={loadError} style={{ marginBottom: 12 }} />

      {years === null ? (
        <PickerLoader label="جاري تحميل السنوات الدراسية" />
      ) : !years.length ? (
        <div style={{ textAlign: "center", color: "rgba(255,255,255,.4)", fontSize: 13, padding: "24px 0" }}>
          لا توجد سنوات دراسية بعد داخل مجلد الاستبيانات الرئيسي.
        </div>
      ) : semesters === null ? (
        <PickerLoader label="جاري تحميل الفصول الدراسية" />
      ) : !semesters.length ? (
        <div style={{ textAlign: "center", color: "rgba(255,255,255,.4)", fontSize: 13, padding: "24px 0" }}>
          لا توجد فصول دراسية داخل هذه السنة بعد.
        </div>
      ) : forms === null ? (
        <PickerLoader />
      ) : forms.length === 0 ? (
        <div style={{ textAlign: "center", color: "rgba(255,255,255,.4)", fontSize: 13, padding: "24px 0" }}>
          لا توجد استبيانات لهذا الفصل بعد.
        </div>
      ) : (
        <div>
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10, flexWrap: "wrap", marginBottom: 12, padding: "10px 12px", borderRadius: 10, background: "rgba(26,188,156,.07)", border: "1px solid rgba(26,188,156,.16)" }}>
            <div style={{ display: "flex", alignItems: "center", gap: 7, flexWrap: "wrap" }}>
              <span style={{ color: "#b9fff2", fontSize: 12, fontWeight: 800 }}>{selectedIds.size} محدد</span>
              <button className="btn btn-ghost btn-sm" onClick={() => setSelectedIds(new Set(forms.map(f => f.id)))}>تحديد الكل</button>
              {!!selectedIds.size && <button className="btn btn-ghost btn-sm" onClick={() => setSelectedIds(new Set())}>إلغاء التحديد</button>}
            </div>
            <div style={{ display: "flex", gap: 7, flexWrap: "wrap" }}>
              <button className="btn btn-primary btn-sm" disabled={!selectedIds.size || analyzing} style={{ opacity: selectedIds.size && !analyzing ? 1 : .45 }} onClick={() => analyzeForms(forms.filter(f => selectedIds.has(f.id)))}>تحليل المحدد ({selectedIds.size})</button>
              <button className="btn btn-ghost btn-sm" disabled={analyzing} onClick={() => analyzeForms(forms)}>تحليل الكل ({forms.length})</button>
            </div>
          </div>
          {forms.map(f => (
            <div key={f.id} style={{
              display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12,
              padding: "12px 14px", borderRadius: 10, background: "rgba(255,255,255,.04)",
              border: "1px solid rgba(255,255,255,.08)", marginBottom: 8,
            }}>
              <input type="checkbox" checked={selectedIds.has(f.id)} aria-label={`تحديد ${f.name}`}
                onChange={() => setSelectedIds(prev => { const next = new Set(prev); if (next.has(f.id)) next.delete(f.id); else next.add(f.id); return next; })}
                style={{ width: 17, height: 17, accentColor: "#1abc9c", cursor: "pointer", flexShrink: 0 }} />
              <div style={{ flex: 1 }}>
                <div style={{ color: "#e8f0fe", fontSize: 13, fontWeight: 700 }}>{f.name}</div>
                <div style={{ color: "rgba(255,255,255,.4)", fontSize: 11, marginTop: 2 }}>{f.surveyType}</div>
              </div>
              <button className="btn btn-primary btn-sm" disabled={loadingFormId === f.id} onClick={() => selectForm(f)}>
                {loadingFormId === f.id ? <>جاري التحميل<span className="loader-dots"><i/><i/><i/></span></> : "اختيار"}
              </button>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
